# Generated by Django 5.0.6 on 2024-07-09 00:49

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Razon Social')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electornico')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono Contacto')),
                ('web', models.URLField(blank=True, verbose_name='Sitio Web')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proovedores',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('barcode', models.CharField(max_length=10, unique=True, verbose_name='Codigo barras')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion del producto')),
                ('unit', models.CharField(choices=[('0', 'Kilogramo'), ('1', 'Libra'), ('2', 'Litros'), ('3', 'Unidades')], max_length=1, verbose_name='Unidad de medida')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Cantidad en almacen')),
                ('purchase_price', models.PositiveIntegerField(default=1, verbose_name='Precio compra')),
                ('sale_price', models.PositiveIntegerField(default=2, verbose_name='Precio venta')),
                ('num_sale', models.PositiveIntegerField(default=0, verbose_name='Numero de ventas')),
                ('anulate', models.BooleanField(default=False, verbose_name='Anulado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.marca')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.provider')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
